### PR TITLE
adds /all

### PR DESCRIPTION
**Pull request by Teddy-Kun**
Adds a /all to download all fields and card artworks

### CODE REVIEW

**Comment by NiiMiyo** [comment]
This does not work since a function can't return two times.
But I liked the idea. I'll see what I can do to make this work.

**Comment by Teddy-Kun** [comment]
Right I am stupid, but don't worry I think I can fix that pretty easily.

**Comment by Teddy-Kun** [comment]
Should be fixed now. I had to change the main method and for cleaner code I moved the output as text into the download method

**Comment by NiiMiyo** [comment]
Resolved with #3.

Had to completely redo the way commands work. At least the code is way cleaner now and it's possible for a single command to download field artwork and card arts.

Thanks for the suggestion.

**Pull request closed without merging**
